- name: install bind
  package:
    name: bind
    state: present
  notify: bind enable

- name: configure firewall
  firewalld:
    service: dns
    immediate: yes
    permanent: yes
    state: enabled

- name: bind config
  copy:
    src: named.conf
    dest: /etc/named.conf
  notify: bind update

- name: zone config
  template:
    src: domain.hosts.j2
    dest: /var/named/{{ domain }}.com
    owner: root
    group: named
  notify: bind update